package pl.edu.agh.monitordb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-04-09T22:52:13.783+02:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://MonitorDB.agh.edu.pl", name = "IMonitorService")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class})
public interface IMonitorService {

    @Action(input = "http://MonitorDB.agh.edu.pl/IMonitorService/AddData", output = "http://MonitorDB.agh.edu.pl/IMonitorService/AddDataResponse")
    @RequestWrapper(localName = "AddData", targetNamespace = "http://MonitorDB.agh.edu.pl", className = "pl.edu.agh.monitordb.AddData")
    @WebMethod(operationName = "AddData", action = "http://MonitorDB.agh.edu.pl/IMonitorService/AddData")
    @ResponseWrapper(localName = "AddDataResponse", targetNamespace = "http://MonitorDB.agh.edu.pl", className = "pl.edu.agh.monitordb.AddDataResponse")
    public void addData(
        @WebParam(name = "year", targetNamespace = "http://MonitorDB.agh.edu.pl")
        java.lang.Integer year,
        @WebParam(name = "month", targetNamespace = "http://MonitorDB.agh.edu.pl")
        java.lang.Integer month,
        @WebParam(name = "day", targetNamespace = "http://MonitorDB.agh.edu.pl")
        java.lang.Integer day,
        @WebParam(name = "hour", targetNamespace = "http://MonitorDB.agh.edu.pl")
        java.lang.Integer hour,
        @WebParam(name = "min", targetNamespace = "http://MonitorDB.agh.edu.pl")
        java.lang.Integer min,
        @WebParam(name = "sec", targetNamespace = "http://MonitorDB.agh.edu.pl")
        java.lang.Float sec,
        @WebParam(name = "computer", targetNamespace = "http://MonitorDB.agh.edu.pl")
        java.lang.String computer,
        @WebParam(name = "counter", targetNamespace = "http://MonitorDB.agh.edu.pl")
        java.lang.String counter,
        @WebParam(name = "value", targetNamespace = "http://MonitorDB.agh.edu.pl")
        java.lang.Float value,
        @WebParam(name = "verify", targetNamespace = "http://MonitorDB.agh.edu.pl")
        java.lang.String verify
    );
}
