//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValuesTable
    {
        public int Id { get; set; }
        public System.DateTime Time { get; set; }
        public string Computer { get; set; }
        public string Counter { get; set; }
        public double CounterValue { get; set; }
    }
}
